### ISSUE TITLE
BTicino X8000 ver.06 not update values

### ISSUE THREAD

**Issue by palve55** [andrea-mattioli/mattiols_hassio_repository#16]
Hi, after a long time of correct work, now the temperature and humidity values are wrong. Always fixed values.  If I repeat "get your code" in the window "Measures" I can read the correct values. Recreate HA Entities and restart not resolve. The commands (manual, program, etc.) are good (they work). Can you help me?

**Comment by andrea-mattioli** [comment]
Hi it's a Legrand issue https://developer.legrand.com/forums/topic/webhook-delay/

Regards

**Comment by palve55** [comment]
Hello, it was not delay. I restarted HASSIO a lot of time without results, but then I tryed to stop and disconnect my rasberry pi and all works fine... Very crazy. Thanks

**Comment by andrea-mattioli** [comment]
From legrand: 

Hello everybody,

We think that your issues are due to a webhook ban. Here are the rules :

If your endpoint doesn’t respond in less than 750ms or respond a code >= 300, we increment it to a failure counter

After 20 failures, we count 1 error for your endpoint and ban it for a total of minutes calculated as following : 1 minute * set of 20 failures (i.e. : 200 failures = 10 minutes ban)

The maximum ban time is 20 minutes. All webhook changes that happened during this ban are lost and will not be sent

I also have now access to a list of banned endpoints during the last 24 hours. If you think that your endpoint can be impacted, please give me your webhook URL here or via the contact form and I’ll check

Have a good day,

Leslie – Community Manager
